[bumpver]
current_version = "0.0.7"
version_pattern = "MAJOR.MINOR.PATCH[-PYTAGNUM]"
commit_message = "🔖 Bump version | {old_version} => {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"instance.json" = [
    '"version": "{version}",'
]
"pack.toml" = [
    'version = "{version}"'
]
"server.json" = [
    '"version": "{version}",'
]
