name = "NowWhat"
author = "fuzzyweapon"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "016ccfd81ac00e8d5615eff55b77568a917766feec25cd0d1497645c3972e2e0"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
