name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ba563610a3bc200214c3b79b6e39f8149dd466127d233b6532f27fdf9bb45ac"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
