name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a1d8a2d6b8f69ee0314189791e783faadf569e82c7f5285ddb38cd4556cbfbf"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
