name = "mc-NowWhat"
author = "fuzzyweapon"
version = "1.19.2-0.1.0-FAT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "204d1dce5caacb6022cd7a17e3ccd7cc7c846940238e90668b2be4486996f25b"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
