name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d99f74ea7c9b067ac7024e2b2d4b8b4146382c583c6cc8dcf29223d2dfa52ab3"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
