name = "mc-NowWhat"
author = "fuzzyweapon"
version = "1.19.2-0.1.0-FAT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b9af415143c184bb19ff531940cfccaab9de9de336f3bb25f4ce4e2473183da"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
