name = "NowWhat"
author = "fuzzyweapon"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e294458d77015decf8181d41d6de49d8c51c24d4a5b38f1142e53609d2757f06"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
