name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45e6ae9cfac8921f0e14da697551ac5ac82c8d6d8d169ca496d6515bbd985300"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
