name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c3b69b8cc19aa66854824ac26d822b4fd63d95f20bf1998e7016320b959a131"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
