name = "NowWhat"
author = "fuzzyweapon"
version = "1.19.2-0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02a9be1c6e20846e2df30a28b619409e886961090f3e4a7cb374d579919d9bc7"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
