name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cc2054915f46b60a26bc5683ade07b0571c4d37bf393b9a6c1c6abba21720c8"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
