name = "NowWhat"
author = "fuzzyweapon"
version = "1.19.2-0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f7416ef8c957b4c221fd8097cdc90762b6fa3a18b01108b108f6fea842b9556"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
