name = "NowWhat"
author = "fuzzyweapon"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd641536349585a572b1b321f38f3b9fa9f7a1348497513f62adca5f5a4d3b6d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
