name = "NowWhat"
author = "fuzzyweapon"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cdea5cbbfcd15d3df2344404c03eefeb38e1b20ef42a2b72fb442c2a92e1022"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
