name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c329e16a1af7650284aea959a17011e0f515838ee97e9a4c03a4e69feba8b4a7"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
