name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.7-a0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db28ab6207e6a945463fd95d006cbaf1abccbb62053692a54c752eb35556a227"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
