name = "NowWhat"
author = "fuzzyweapon"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6a731454c69cc2a42aee9e4a3be68145cc2a59875f94bbcf125593639946573"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
