name = "NowWhat"
author = "fuzzyweapon"
version = "1.19.2-0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e092eddc96b35e92ad308164d368766e89c7d84f6fee8ea4e18033b535004ceb"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
