name = "NowWhat"
author = "fuzzyweapon"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c20bd14ba149ea5dfd0907e0b893334309b4058c12cb2618744c19677bbed0f6"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
