name = "NowWhat"
author = "fuzzyweapon"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e961c51deb19b27a4b9ddfa4952e1f83b420a3a1956772ae5bea267d3fbb984d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
