enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
yigd = true
minecraft = true
